palabras = {
    "animales": ["gato", "perro", "vaca", "pato", "oveja", "conejo", "pez", "oso", "jirafa", "erizo", "mariposa", "foca", "tigre", "cobra", "almeja", "paloma", "cisne", "mosquito", "hormiga"],
    "colores": ["azul", "verde", "negro", "blanco", "rojo", "amarillo", "morado", "naranja", "rosado", "gris"],
    "profesiones": ["azafata", "artista", "panadero", "carpintero", "cocinero", "maestro", "bombero", "juez", "modelo", "monje", "pintor", "piloto", "secretaria", "taxista", "escritor", "jefe", "aprendiz", "jubilado"],
    "frutas": ["manzana", "pera", "naranja", "platano", "fresa", "uva", "melón", "sandía", "cereza", "mango"],
    "verduras": ["zanahoria", "lechuga", "espinaca", "brócoli", "coliflor", "pimiento", "tomate", "pepino", "calabacín", "berenjena"],
    "ropa": ["camisa", "pantalón", "falda", "chaqueta", "abrigo", "sombrero", "bufanda", "guantes", "zapatos", "calcetines"],
    "partes del cuerpo": ["cabeza", "brazo", "pierna", "mano", "pie", "ojo", "nariz", "boca", "oreja", "dedo"],
    "países": ["argentina", "brasil", "canadá", "dinamarca", "egipto", "francia", "alemania", "honduras", "italia", "japón"],
    "ciudades": ["lima", "parís", "tokio", "nueva york", "londres", "berlín", "madrid", "pekin", "moscú", "sydney"],
    "deportes": ["fútbol", "baloncesto", "tenis", "natación", "ciclismo", "atletismo", "golf", "voleibol", "boxeo", "hockey"],
    "instrumentos musicales": ["guitarra", "piano", "violín", "flauta", "batería", "saxofón", "trompeta", "clarinete", "arpa", "trombón"],
    "medios de transporte": ["coche", "avión", "barco", "bicicleta", "tren", "autobús", "motocicleta", "metro", "camión", "helicóptero"],
    "electrodomésticos": ["lavadora", "secadora", "microondas", "horno", "frigorífico", "lavavajillas", "tostadora", "batidora", "aspiradora", "televisor"],
    "herramientas": ["martillo", "destornillador", "alicate", "llave", "sierra", "taladro", "cinta métrica", "nivel", "escalera", "cuchillo"],
    "juguetes": ["muñeca", "camión", "pelota", "rompecabezas", "lego", "juguete", "osito", "barbie", "patinete", "videojuego"],
    "planetas": ["mercurio", "venus", "tierra", "marte", "júpiter", "saturno", "urano", "neptuno", "plutón", "luna"],
    "bebidas": ["agua", "leche", "jugo", "refresco", "café", "té", "cerveza", "vino", "whisky", "licor"],
    "muebles": ["silla", "mesa", "sofá", "cama", "armario", "escritorio", "estantería", "lámpara", "butaca", "taburete"],
    "vehículos": ["coche", "camión", "moto", "bicicleta", "autobús", "tren", "barco", "avión", "triciclo", "patinete"],
    "fenómenos naturales": ["tormenta", "terremoto", "volcán", "tsunami", "huracán", "tornado", "lluvia", "nieve", "relámpago", "granizo"],
    "objetos de cocina": ["cuchillo", "tenedor", "cuchara", "plato", "vaso", "olla", "sartén", "batidora", "licuadora", "colador"],
    "tecnología": ["computadora", "teléfono", "tablet", "teclado", "ratón", "impresora", "monitor", "altavoz", "cámara", "reloj inteligente"]
}
